"""streak

Revision ID: 175267a45879
Revises: 5e19ade268b6
Create Date: 2026-07-31 23:00:24.829749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '175267a45879'
down_revision: Union[str, Sequence[str], None] = '5e19ade268b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_study_day',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('study_date', sa.Date(), nullable=False),
    sa.Column('reviews_count', sa.Integer(), nullable=False),
    sa.Column('unique_cards_count', sa.Integer(), nullable=False),
    sa.Column('qualifies_for_streak', sa.Boolean(), nullable=False),
    sa.Column('first_reviewed_at_utc', sa.DateTime(), nullable=True),
    sa.Column('last_reviewed_at_utc', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'study_date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_study_day')
    # ### end Alembic commands ###
