"""study_session

Revision ID: 42fec71877b8
Revises: a1b2c3d4e5f6
Create Date: 2026-07-17 01:48:21.757251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42fec71877b8'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('study_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deck_id', sa.Integer(), nullable=False),
    sa.Column('current_position', sa.Integer(), nullable=False),
    sa.Column('page', sa.Enum('cards', 'results', native_enum=False), nullable=False),
    sa.ForeignKeyConstraint(['deck_id'], ['deck.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('deck_id')
    )
    op.create_table('study_session_card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('study_session_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Enum('red', 'yellow', 'green', native_enum=False), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['card.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['study_session_id'], ['study_session.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('study_session_card')
    op.drop_table('study_session')
    # ### end Alembic commands ###
