"""push_subscription

Revision ID: 5e19ade268b6
Revises: b3c4d5e6f7a8
Create Date: 2026-07-30 00:04:46.450539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e19ade268b6'
down_revision: Union[str, Sequence[str], None] = 'b3c4d5e6f7a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('notification_time', sa.Time(), nullable=False),
    sa.Column('deck_notification_condition_enabled', sa.Boolean(), nullable=False),
    sa.Column('deck_notification_condition_cards', sa.Integer(), nullable=False),
    sa.Column('deck_notification_condition_days', sa.Integer(), nullable=False),
    sa.Column('card_notification_condition_enabled', sa.Boolean(), nullable=False),
    sa.Column('card_notification_condition_days', sa.Integer(), nullable=False),
    sa.Column('streak_notification_condition_enabled', sa.Boolean(), nullable=False),
    sa.Column('streak_notification_condition_days', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('push_subscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('settings_id', sa.Integer(), nullable=False),
    sa.Column('host', sa.String(), nullable=False),
    sa.Column('endpoint', sa.String(), nullable=False),
    sa.Column('keys_p256dh', sa.String(), nullable=False),
    sa.Column('keys_auth', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['settings_id'], ['settings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('endpoint', 'keys_p256dh', 'keys_auth')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('push_subscription')
    op.drop_table('settings')
    # ### end Alembic commands ###
