"""study_session

Revision ID: 93d477fecec2
Revises: f5dd2db97748
Create Date: 2026-07-17 18:49:19.809431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93d477fecec2'
down_revision: Union[str, Sequence[str], None] = 'f5dd2db97748'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('study_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deck_id', sa.Integer(), nullable=False),
    sa.Column('old_mastery', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['deck_id'], ['deck.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('deck_id')
    )
    op.create_table('study_session_card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('study_session_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Enum('red', 'yellow', 'green', native_enum=False), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['card.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['study_session_id'], ['study_session.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('study_session_card')
    op.drop_table('study_session')
    # ### end Alembic commands ###
