interface Card {
  id: number;
  question: string;
  answer: string;
}

type CardCreate = Omit<Card, "id">;

const cards: CardCreate[] = [
  {
    question: "What are the three primary responsibilities of an operating system?",
    answer: "1. Process management\n2. Memory management\n3. File system and device management",
  },
  {
    question: "What are 2 ways of addressing I/O devices?",
    answer: "1. Direct I/O instructions\n2. Memory-mapped I/O",
  },
  {
    question: "The interface an OS uses to communicate with a device is known as a",
    answer: "Device driver",
  },
  {
    question: "An interrupt generated by the currently executing instruction is a",
    answer: "Synchronous interrupt",
  },
  {
    question: "What are the 3 multithreading models?",
    answer: "1. Many to one\n2. One to one\n3. Many to many",
  },
  {
    question: "What is the optimal scheduling algorithm?",
    answer: "Shortest Job First (SJF)",
  },
  {
    question: "Which scheduling algorithm is used in a timesharing environment?",
    answer: "Round Robin (RR)",
  },
];

export function getCards(): Card[] {
  return cards.map((card, i) => ({
    id: i + 1,
    ...card
  }));
}