export interface Deck {
  id: number;
  name: string;
  mastery: number;
  cards: Card[];
}

export interface Card {
  id: number;
  question: string;
  answer: string;
}

interface DeckCreate {
  name: string;
  mastery: number;
  cards: CardCreate[];
};

type CardCreate = Omit<Card, "id">;

let nextDeckId = 1;
let nextCardId = 1;

function createDeck(deck: DeckCreate): Deck {
  return {
    id: nextDeckId++,
    name: deck.name,
    mastery: deck.mastery,
    cards: deck.cards.map(createCard),
  };
}

function createCard(card: CardCreate): Card {
  return {
    id: nextCardId++,
    ...card
  };
}

const decksToCreate: DeckCreate[] = [
  {
    name: "Operating Systems",
    mastery: 61,
    cards: [
      {
        question: "What are the three primary responsibilities of an operating system?",
        answer: "1. Process management\n2. Memory management\n3. File system and device management",
      },
      {
        question: "What are 2 ways of addressing I/O devices?",
        answer: "1. Direct I/O instructions\n2. Memory-mapped I/O",
      },
      {
        question: "The interface an OS uses to communicate with a device is known as a",
        answer: "Device driver",
      },
      {
        question: "An interrupt generated by the currently executing instruction is a",
        answer: "Synchronous interrupt",
      },
      {
        question: "What are the 3 multithreading models?",
        answer: "1. Many to one\n2. One to one\n3. Many to many",
      },
      {
        question: "What is the optimal scheduling algorithm?",
        answer: "Shortest Job First (SJF)",
      },
      {
        question: "Which scheduling algorithm is used in a timesharing environment?",
        answer: "Round Robin (RR)",
      },
    ]
  }
];

const decks: Deck[] = decksToCreate.map(createDeck);

export function getDeckById(id: number): Deck | null {
  return decks.find(deck => deck.id === id) ?? null;
}